sudo: required
services:
  - docker

before_install:
  - docker build -t subhashgutti/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true subhashgutti/docker-react npm run test -- --coverage

